server:
  port: 9094

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/akhilanilkumar/service-configuration
          repos:
            party-service:
              uri: https://github.com/akhilanilkumar/service-configuration/tree/master/party-service
            leader-service:
              uri: https://github.com/akhilanilkumar/service-configuration/tree/master/leader-service
            development-service:
              uri: https://github.com/akhilanilkumar/service-configuration/tree/master/development-service

management:
  endpoints:
    web:
      exposure:
        include: "*"